<?php
// $Id$

/**
* @file
* Convert ounces to milliliters
*/

/**
* Implementation of hook_menu()
*/
function ounces_to_ml_menu() {
  $items = array();
 
  $items['convert'] = array(
    'title' => 'Converts ounces to milliliters',
    'page callback' => 'ounces_to_ml_page',
    'access arguments' => array('view content'),
  );
 
  return $items;
}


function ounces_to_ml_form($form, &$form_state) {
 
    $form['ounces'] = array(
        '#type' => 'textfield',
        '#title' => t('Ounces'),
        '#description' => t('The numbeor of ounces to convert to milliliters')
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Convert')
    );
    return $form;
}

function ounces_to_ml_page() {
    return drupal_get_form('ounces_to_ml_form');
}
function ounces_to_ml_form_submit($form, &$form_state) {
 
    $output = $form_state['values']['ounces'];
    db_query("INSERT INTO table_name (convert_val) VALUES ('$output') ")
  ->execute();
   drupal_set_message($output);
}
?>